// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200222051726_SeedValueEntity")]
    partial class SeedValueEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "EM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chris"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Regime"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Berni"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
